# Generated by Django 5.2.3 on 2025-06-11 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('view_name', models.CharField(max_length=100)),
                ('filter_params', models.JSONField()),
                ('visibility', models.CharField(choices=[('personal', 'Personal'), ('group', 'Group-based'), ('global', 'Global')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_summary_report', models.BooleanField(default=False)),
                ('summary_config', models.JSONField(blank=True, null=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that can access this report (only for group-based reports)', to='auth.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_bdt_report',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='better_django_tables.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'django_bdt_report_favorite',
                'unique_together': {('user', 'report')},
            },
        ),
    ]
