# Generated by Django 5.2.3 on 2025-07-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('better_django_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can access this report (only for group-based reports)', related_name='bdt_reports', to='auth.group'),
        ),
    ]
