# Generated by Django 5.2.3 on 2025-07-24 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_django_tables', '0002_alter_report_allowed_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdt_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bdt_report_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
